#!/usr/bin/env sh

# abort on errors
set -e

# build
yarn build

git_version_hash=$(git rev-parse HEAD)

# navigate into the build output directory
cd dist

# if you are deploying to a custom domain
echo 'mizikgame.com' > CNAME
echo "$git_version_hash" > VERSION

git init
git checkout -b gh-pages
git add -A
git commit -m 'deploy'

# if you are deploying to https://<USERNAME>.github.io/<REPO>
git push -f git@github.com:awwaiid/mizik.git gh-pages

cd -
